/**
 * Vercel Serverless Function adapter for the Express API.
 *
 * This imports the pre-built Express app bundle and exports it as the default
 * handler for Vercel's Node.js runtime. All /api/* routes are handled here.
 */

// @ts-ignore — the bundle is generated by the build:vercel script
import app from "../artifacts/api-server/dist/app.mjs";

export default app;
